### ISSUE TITLE
Ödev1 son sorunun cevabı yanlış 

### ISSUE THREAD

**Issue by sellta** [PhyeX/PatikaDev-SQL#1]
DOĞRU CEVAP

SELECT * FROM film 
WHERE  NOT (rental_rate = 4.99 OR rental_rate = 2.99) AND length < 51

**Comment by PhyeX** [comment]
Evet fark ettim ve düzelttim bildirdiğin için teşekkürler.

sellta ***@***.***>, 28 Tem 2021 Çar, 08:11 tarihinde şunu
yazdı:
